apiVersion: v1
kind: Service
metadata:
  name: nginx-test-svc
spec:
  selector:
    app: nginx
  ports:
  - port: 80          # Service port
    targetPort: 80    # Container port
  type: LoadBalancer  # Expose publicly on Azure
